name: EnchantmentSolution
version: 2.2.10
main: org.ctp.enchantmentsolution.EnchantmentSolution
api-version: 1.13
softdepend: [mcMMO, Jobs, VeinMiner, AuctionHouse]
commands:
  enchantmentsolution:
    aliases: [es]
    description: All commands for EnchantmentSolution
    usage: /enchantmentsolution
permissions:
  enchantmentsolution.command.edit: 
    description: Gives access to the /es config command. 
    default: op
  enchantmentsolution.command.enchant: 
    description: Gives access to the /es enchant command. 
    default: op
  enchantmentsolution.command.enchant.others: 
    description: Gives access to the /es enchant command for use on other people. 
    default: op
  enchantmentsolution.command.reload: 
    description: Gives access to the /es reload command. 
    default: op
  enchantmentsolution.command.enchantremove: 
    description: Gives access to the /es removeenchant command. 
    default: op
  enchantmentsolution.command.enchantremove.others: 
    description: Gives access to the /es removeenchant command for use on other people. 
    default: op
  enchantmentsolution.command.reset: 
    description: Gives access to the /es reset command. 
    default: op
  enchantmentsolution.command.enchantunsafe: 
    description: Gives access to the /es enchantunsafe command.
    default: op
  enchantmentsolution.command.enchantunsafe.others: 
    description: Gives access to the /es enchantunsafe command for use on other people. 
    default: op
  enchantmentsolution.command.calculator:
    description: Allows players to use the /es calc command
    default: op
  enchantmentsolution.enable-flight:
    description: Enables use of external /fly commands without interference from FrequentFlyer
    default: false
  enchantmentsolution.permissions.ignore: 
    description: Gives access to all enchantment permissions.
    default: false
  enchantmentsolution.demigod-anvil:
    description: Allows players to repair items with enchantments they cannot combine
    default: false
  enchantmentsolution.demigod-books:
    description: Allows players to add levels from enchanted books to items even if they cannot combine the levels
    default: false
  enchantmentsolution.god-anvil:
    description: Allows players to combine items higher than their max levels
    default: false
  enchantmentsolution.command.debug:
    description: Allows players to use the /es debug command
    default: op
  enchantmentsolution.command.book:
    description: Allows players to use the /es book command
    default: op
  enchantmentsolution.command.anvil:
    description: Allows players to use the /es anvil command
    default: op
  enchantmentsolution.command.grindstone:
    description: Allows players to use the /es grindstone command
    default: op
  enchantmentsolution.command.configlore:
    description: Allows players to use the /es lore command
    default: op
  enchantmentsolution.command.help:
    description: Allows players to use the /es help command
    default: true
  enchantmentsolution.command.info:
    description: Allows players to use the /es info command
    default: true