enchanting_table:
    custom_gui: true
    level_fifty: true
    lapis_in_table: true
    reset_on_reload: true
anvil:
    custom_gui: true
    level_divisor: 4
    default_use: false
    max_repair_level: 60
    damage: true
    rename: true
grindstone:
    custom_gui: true
    use_legacy: false
    take_enchantments: false
    set_repair_cost: true
    destroy_take_item: true
max_enchantments: 0
update_legacy_enchantments: false
use_enchanted_books: false
disable_enchant_method: 'visible'
drop_items_naturally: true
language: 'en_us'
language_file: 'language.yml'
trades:
    villager: false
    piglin: true
use_comments: true
protection_conflicts: true
lore_location: 'top'
version:
    get_latest: true
    get_experimental: false
wiki:
    on_login: true
    on_timer: false
    timer_seconds: 14400
    url: 'https://bit.ly/2N54NzC'
loots:
    mobs:
        use: true
        bookshelves: 0
        levels: 0
    fishing:
        use: true 
        bookshelves: 0
        levels: 0
    chests:
        use: true
        end_city_treasure: 
            bookshelves: 15
            levels: 3
        simple_dungeon: 
            bookshelves: 0
            levels: 0
        shipwreck_supply: 
            bookshelves: 0
            levels: 0
        woodland_mansion: 
            bookshelves: 10
            levels: 1
        stronghold_library: 
            bookshelves: 10
            levels: 1
        stronghold_crossing: 
            bookshelves: 10
            levels: 1
        stronghold_corridor: 
            bookshelves: 10
            levels: 1
        underwater_ruin_big: 
            bookshelves: 0
            levels: 0
        underwater_ruin_small: 
            bookshelves: 0
            levels: 0
        pillager_outpost: 
            bookshelves: 10
            levels: 1
        bastion_bridge: 
            bookshelves: 10
            levels: 2
        bastion_hoglin_stable: 
            bookshelves: 10
            levels: 2
        bastion_other: 
            bookshelves: 10
            levels: 2
        bastion_treasure: 
            bookshelves: 12
            levels: 3
        ruined_portal: 
            bookshelves: 6
            levels: 1

gametypes: []
use_particles: true
play_sounds: true
print_usage: true
multi_block:
    async: false
    all_faces: false
    blocks_per_tick:
        player: 30
        global: 250

config_comments: 

    enchanting_table: 
        custom_gui: 
        - 'Whether to use the custom augmenting table gui'
        - 'This will always be true if level_fifty is true'

        level_fifty: 
        - 'Whether to use the level fifty system of augments'
        
        lapis_in_table: 
        - 'If players need to insert lapis into the custom table for it to work'
        
        reset_on_reload: 
        - 'Resets augments in augmenting table whenever the server is reloaded'
        - 'Setting this to false means the only ways to reset augments are through /esreset and augmenting an item'
    anvil: 
        custom_gui: 
        - 'Whether to use the custom anvil gui'
        
        level_divisor: 
        - 'Greater numbers allow more anvil uses'

        max_repair_level: 
        - 'The highest repair level that will be allowed in the anvil'
        - 'Will show ''Too Expensive to Repair'' if using above 39 and using the vanilla GUI'

        default_use: 
        - 'Allow default use of anvil GUI via option at bottom right of custom GUI'
        - 'Only used when custom_gui is true'
        - 'Should only be true if anvil is used for custom recipes'

        damage: 
        - 'The anvil will be damaged while using it - normal vanilla behavior on true'

        rename: 
        - 'Whether players can use the custom rename without a permission'

    grindstone: 
        custom_gui: 
        - 'Whether to use the custom grindstone gui'
        - 'Will always use the custom gui in 1.13.2 and below'
        
        use_legacy: 
        - 'Whether to use the custom grindstone gui in 1.13.2 and earlier'
        - 'Will always be false above 1.13.2'
        
        take_enchantments: 
        - 'Use the grindstone to add augments from items to books'
        - 'Only used when custom_gui is true'

        set_repair_cost: 
        - 'When grindstone takes augments, set repair cost of the generated book to the item used''s repair cost'

        destroy_take_item: 
        - 'When grindstone takes augments, destroy the item used'

    max_enchantments: 
    - 'Max enchantments on each item. 0 allows infinite'

    update_legacy_enchantments: 
    - 'Update any enchantments generated in EnchantmentSolutionLegacy'

    use_enchanted_books: 
    - 'Uses the vanilla Augmentation Manuals rather than Books to store augments'

    disable_enchant_method: 
    - 'How disabling an augment in enchantments.yml or enchantments_advanced.yml will work'
    - 'Options:'
    - 'vanish - removes augment from items'
    - 'visible - keeps augment on item, but custom effects will not work and anvil will remove augment'
    - 'repairable - same as above but anvil will not remove augment'

    drop_items_naturally: 
    - 'Items will drop in the default Minecraft way rather than drop straight to the ground'
    - 'May cause issues with items flying away'

    language_file: 
    - 'The yml language file'

    language: 
    - 'The default language of the language file'

    trades: 
        villager:
        - 'Allow custom and/or high level augments to appear in villager trades'
        piglin:
        - 'Allow custom and/or high level augments to appear in piglin bartering loot'

    use_comments: 
    - 'Show helpful comments in the config files'

    protection_conflicts: 
    - 'All protection types conflict with each other'

    lore_location: 
    - 'Modify where custom augments will be in the item''s lore'
    - '- top: At the top of the lore right under normal augments'
    - '- bottom: At the very bottom of the lore'
    - '- unset: Augments will be placed wherever they are (can change randomly when trying to fix them)'

    version: 
        get_latest: 
        - 'Check github for plugin releases (available on github and spigot)'

        get_experimental: 
        - 'Check github for plugin experimental versions (available only on github)'

    wiki: 
        on_login: 
        - 'Shows the wikipedia page to the user on login'

        on_timer: 
        - 'Shows the wikipedia page to the user on a timer'

        timer_seconds: 
        - 'The number of seconds between when users should be alerted to the wiki'

        url: 
        - 'The URL to the wiki - the default is the normal EnchantmentSolution wiki'

    loots: 
        mobs: 
            use: 
            - 'Allow custom and/or high level augments to spawn on mobs'
            bookshelves: 
            - 'Modify types of augments generated by setting the minimum amount of bookshelves'

            levels: 
            - 'Modify types of augments generated by setting the minimum lapis level'

        fishing: 
            use:
            - 'Allow custom and/or high level augments to appear while fishing'
            
            bookshelves: []

            levels: []
        chests: 
            use:
            - 'Allow custom and/or high level augments to spawn in chests'
            
    gametypes: 
    - 'What extra gametypes should be applied to the plugin.'
    - 'MINIGAME: Augments are given through a special inventory. Customize with minigame.yml.'
    - '    Clicking books over augmentable items will anvil them.'
    - 'RPG: Only certain augments are enabled by default.'
    - '    Using augments will increase your level to buy new augments and levels.'
    - 'HARD: Not implemented fully. A certain percentage of mobs will spawn with increased health.'
    use_particles: 
    - 'Whether augments like Hoarding and High Reach will spawn particles around broken blocks.'
    - 'May cause large amounts of lag with higher levels of Depth/Height/Width++.'
    play_sounds: 
    - 'Whether augments like Hoarding and High Reach will play sounds for broken blocks.'
    print_usage: 
    - 'Print usage to player when getting a command wrong.'
    - 'Only works for commands for which they have permission.'
    
    multi_block:
        async:
        - 'Whether the Far/High/Wide Reach augments should work asynchronously'
        - 'This increases performance but nerfs those augments slightly'
        - 'DEPRECATED - now will always be true for performance reasons'
        all_faces:
        - 'Whether the async will only check basic block faces (North, South, East, West, Up, Down) or all faces.'
        blocks_per_tick:
            player:
            - 'The maximum blocks broken per tick per player using Far/High/Wide Reach'
            global:
            - 'The maximum blocks broken per tick globally using Far/High/Wide Reach'
